version: '3.8'
services:
  auth-service:
    build: ./auth-service
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=db
    depends_on:
      - db

  user-service:
    build: ./user-service
    ports:
      - "8082:8082"
    environment:
      - DB_HOST=db
    depends_on:
      - db

  content-service:
    build: ./content-service
    ports:
      - "8083:8083"
    environment:
      - DB_HOST=db
    depends_on:
      - db

  comments-service:
    build: ./comments-service
    ports:
      - "8084:8084"
    environment:
      - DB_HOST=db
    depends_on:
      - db

  search-service:
    build: ./search-service
    ports:
      - "8085:8085"
    environment:
      - DB_HOST=db
    depends_on:
      - db

  analytics-service:
    build: ./analytics-service
    ports:
      - "8086:8086"
    environment:
      - DB_HOST=db
    depends_on:
      - db

  notifications-service:
    build: ./notifications-service
    ports:
      - "8087:8087"
    environment:
      - DB_HOST=db
    depends_on:
      - db

  recommendation-service:
    build: ./recommendation-service
    ports:
      - "8088:8088"
    environment:
      - DB_HOST=db
    depends_on:
      - db

  media-service:
    build: ./media-service
    ports:
      - "8089:8089"
    environment:
      - DB_HOST=db
    depends_on:
      - db

  payments-service:
    build: ./payments-service
    ports:
      - "8090:8090"
    environment:
      - DB_HOST=db
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
